# Generated by Django 4.0.3 on 2022-07-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordsafe', '0003_alter_passwordsafe_user_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordsafe',
            name='platform_name',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('Amazon', 'Amazon'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('google', 'Google')], default='google', max_length=50),
        ),
    ]
