# Generated by Django 4.0.3 on 2022-07-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordsafe', '0004_alter_passwordsafe_platform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordsafe',
            name='platform_name',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Amazon', 'Amazon'), ('YouTube', 'YouTube'), ('Instagram', 'Instagram'), ('Google', 'Google')], default='google', max_length=50),
        ),
    ]
