# Generated by Django 4.0.3 on 2023-03-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('attending', models.BooleanField(default=False)),
                ('meal_choice', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('attending', models.BooleanField(default=False)),
                ('song_request', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
