# Generated by Django 4.0.3 on 2023-03-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boy',
            old_name='meal_choice',
            new_name='song_request',
        ),
    ]
