# Generated by Django 4.0.3 on 2023-04-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_meal_choice_boy_song_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boy',
            name='attending',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='girl',
            name='attending',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
