# Generated by Django 4.0.3 on 2023-04-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_boy_attending_alter_girl_attending'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrideSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attending', models.CharField(choices=[('yes', 'Yes, I will be attending'), ('no', 'No, I will not be attending'), ('not_sure', 'Not sure yet')], max_length=10)),
                ('total_attending', models.IntegerField()),
                ('song_request', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GroomSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attending', models.CharField(choices=[('yes', 'Yes, I will be attending'), ('no', 'No, I will not be attending'), ('not_sure', 'Not sure yet')], max_length=10)),
                ('total_attending', models.IntegerField()),
                ('coach_attending', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Boy',
        ),
        migrations.DeleteModel(
            name='Girl',
        ),
    ]
