# Generated by Django 4.0.3 on 2023-04-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_brideside_groomside_delete_boy_delete_girl'),
    ]

    operations = [
        migrations.AddField(
            model_name='groomside',
            name='song_request',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='brideside',
            name='song_request',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
