# Generated by Django 4.0.3 on 2023-04-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_brideside_attending_alter_groomside_attending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brideside',
            name='attending',
            field=models.CharField(choices=[('yes', 'Accept with Pleasure'), ('no', 'Regretfully Decline')], max_length=10),
        ),
        migrations.AlterField(
            model_name='groomside',
            name='attending',
            field=models.CharField(choices=[('yes', 'Accept with Pleasure'), ('no', 'Regretfully Decline')], max_length=10),
        ),
    ]
