# Generated by Django 4.0.3 on 2023-05-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_brideside_attending_alter_groomside_attending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brideside',
            name='attending',
        ),
        migrations.RemoveField(
            model_name='brideside',
            name='song_request',
        ),
        migrations.RemoveField(
            model_name='brideside',
            name='total_attending',
        ),
        migrations.RemoveField(
            model_name='groomside',
            name='attending',
        ),
        migrations.RemoveField(
            model_name='groomside',
            name='coach_attending',
        ),
        migrations.RemoveField(
            model_name='groomside',
            name='song_request',
        ),
        migrations.RemoveField(
            model_name='groomside',
            name='total_attending',
        ),
        migrations.AddField(
            model_name='brideside',
            name='attending_gurdwara_bride',
            field=models.CharField(choices=[('yes', 'Accept with Pleasure'), ('no', 'Regretfully Decline')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='brideside',
            name='attending_reception_bride',
            field=models.CharField(choices=[('yes', 'Accept with Pleasure'), ('no', 'Regretfully Decline')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='brideside',
            name='song_request_bride',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brideside',
            name='total_attending_gurdwara_bride',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brideside',
            name='total_attending_reception_bride',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groomside',
            name='attending_gurdwara_groom',
            field=models.CharField(choices=[('yes', 'Accept with Pleasure'), ('no', 'Regretfully Decline')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='groomside',
            name='attending_reception_groom',
            field=models.CharField(choices=[('yes', 'Accept with Pleasure'), ('no', 'Regretfully Decline')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='groomside',
            name='coach_attending_gurdwara_groom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groomside',
            name='coach_attending_reception_groom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groomside',
            name='song_request_groom',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='groomside',
            name='total_attending_gurdwara_groom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groomside',
            name='total_attending_reception_groom',
            field=models.IntegerField(default=0),
        ),
    ]
